model:
  base_momentum: 0.996
  backbone:
    type: "resnet50"
    pretrained: false
  projection:
    type: "MLP"
    input_dim: 2048
    hidden_dim: 4096
    output_dim: 256
  predictor:
    type: "MLP"
    input_dim: 256
    hidden_dim: 4096
    output_dim: 256

amp:
  sync_bn: True
  opt_level: "O0"

data:
  use_local_dataloader: True
  image_dir: "/home/admin/workspace/shared/imagenet/"
  resize_size: 224
  data_workers: 8
  train_batch_size: 128
  val_batch_size: 64
  dual_views: true
  # for oss
  train_root: "imagenet/imagenet_train/"
  val_root: "imagenet/imagenet_val/"
  train_list: "imagenet/imagenet_train.txt"
  val_list: "imagenet/imagenet_val.txt"
  endpoint:
  key_id:
  secret_id:
  bucket:

optimizer:
  type: lars
  base_lr: 0.2
  momentum: 0.9
  weight_decay: 1.5e-6
  total_epochs: 300
  warmup_epochs: 10
  exclude_bias_and_bn: true

checkpoint:
  time_stamp:
  resume_path:
  save_epoch: 1
  ckpt_prefix: "byol_imagenet/{}/{}_{}.pth.tar"
  ckpt_endpoint:
  ckpt_key_id:
  ckpt_secret_id:
  ckpt_bucket:

log:
  log_step: 10
  acc_log_file: "byol_imagenet/{}/log/acc_log_file.log"
  acc_log_png: "byol_imagenet/{}/log/acc_log_file.png"
  loss_log_file: "byol_imagenet/{}/log/loss_log_file.log"
  loss_log_png: "byol_imagenet/{}/log/loss_log_file.png"
  lr_log_file: "byol_imagenet/{}/log/lr_log_file.log"
  lr_log_png: "byol_imagenet/{}/log/lr_log_file.png"

stage: "train"
distributed: true
